baseURL: "https://docs.spanda.io"
paginate: 100
enableEmoji: true

metaDataFormat: "yaml"
title: "Spanda Docs"
theme: "drone-hugo-theme"

pygmentsCodeFences:  true
pygmentsOptions: ""
# Use the Chroma stylesheet
pygmentsUseClasses:  true
pygmentsUseClassic:  false
# See https://help.farbox.com/pygments.html
pygmentsStyle:  "friendly"

copyright:  " Copyright © 2018 Spanda.IO Inc."

menu:
    k8s:
        - identifier: k8s_overview
            weight: 101
    
    flask:
        - identifier: flask_overview
            weight: 201
    
    cli:
        - identifier: cli_overview
            weight: 301
    
    misc:
        - identifier: misc_overview
            weight: 401

    index:
        - identifier: section_k8s
            url: /k8s/
            weight: 101
        - identifier: section_flask
            url: /flask/
            weight: 102
        - identifier: section_cli
            url: /cli/
            weight: 103
        - identifier: section_misc
            url: /misc/
            weight: 104


